name: dummy-products-stage

services:
  web:
    image: ${DOCKER_USERNAME}/dummy-products-web:stage
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - app

  docs:
    image: ${DOCKER_USERNAME}/dummy-products-docs:stage
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: "3000"
    expose:
      - "3000"
    networks:
      - app

networks:
  app:
    driver: bridge
