export const tokenCssVars = {
  color: {
    surface: "var(--ui-color-surface)",
    surfaceMuted: "var(--ui-color-surface-muted)",
    surfaceApp: "var(--ui-color-surface-app)",
    surfaceAuth: "var(--ui-color-surface-auth)",
    border: "var(--ui-color-border)",
    borderControl: "var(--ui-color-border-control)",
    borderStrong: "var(--ui-color-border-strong)",
    borderSubtle: "var(--ui-color-border-subtle)",
    borderSecondary: "var(--ui-color-border-secondary)",
    borderFaint: "var(--ui-color-border-faint)",
    primary: "var(--ui-color-primary)",
    primaryBorder: "var(--ui-color-primary-border)",
    accent: "var(--ui-color-accent)",
    onPrimary: "var(--ui-color-on-primary)",
    focusRing: "var(--ui-color-focus-ring)",
    text: "var(--ui-color-text)",
    textSecondary: "var(--ui-color-text-secondary)",
    textSubtle: "var(--ui-color-text-subtle)",
    textMuted: "var(--ui-color-text-muted)",
    textTertiary: "var(--ui-color-text-tertiary)",
    textPlaceholder: "var(--ui-color-text-placeholder)",
    textFaint: "var(--ui-color-text-faint)",
    success: "var(--ui-color-success)",
    successSurface: "var(--ui-color-success-surface)",
    info: "var(--ui-color-info)",
    warning: "var(--ui-color-warning)",
    danger: "var(--ui-color-danger)",
    dangerSurface: "var(--ui-color-danger-surface)",
    link: "var(--ui-color-link)",
    overlay: "var(--ui-color-overlay)",
    cardSurface: "var(--ui-color-card-surface)",
    cardBorder: "var(--ui-color-card-border)",
    checkboxChecked: "var(--ui-color-checkbox-checked)",
  },
  space: {
    xs: "var(--ui-space-xs)",
    sm: "var(--ui-space-sm)",
    md: "var(--ui-space-md)",
    lg: "var(--ui-space-lg)",
    xl: "var(--ui-space-xl)",
    xxl: "var(--ui-space-xxl)",
  },
  radius: {
    xs: "var(--ui-radius-xs)",
    sm: "var(--ui-radius-sm)",
    md: "var(--ui-radius-md)",
    lg: "var(--ui-radius-lg)",
    xl: "var(--ui-radius-xl)",
    pill: "var(--ui-radius-pill)",
  },
  font: {
    heading: "var(--ui-font-heading)",
    ui: "var(--ui-font-ui)",
    body: "var(--ui-font-body)",
    roboto: "var(--ui-font-roboto)",
    mono: "var(--ui-font-mono)",
  },
} as const;
