import fs from "node:fs";
import path from "node:path";
import { argv } from "node:process";

const ROOT = process.cwd();
const SOURCE = path.join(ROOT, "docs", "ROADMAP.md");
const OUT_DEFAULT = path.join(ROOT, "docs", "ROADMAP.generated.md");
const outArgIndex = argv.indexOf("--out");
const OUT =
  outArgIndex !== -1 && argv[outArgIndex + 1]
    ? path.resolve(argv[outArgIndex + 1])
    : OUT_DEFAULT;

const SECTION_ORDER = ["In Progress", "Planned", "Done"];
const STATUS_LABELS = {
  "In Progress": "In Progress",
  Planned: "Planned",
  Done: "Done",
};
const LINE_SPLIT = /\r?\n/;
const SECTION_RE = /^##\s+(.*)\s*$/;
const ITEM_RE = /^- \[( |x)\]\s+\[area:([^\]]+)\]\s+(.*)$/;

function parseRoadmap(md) {
  const lines = md.split(LINE_SPLIT);
  let current = null;
  const items = [];

  for (const line of lines) {
    const section = line.match(SECTION_RE);
    if (section) {
      const name = section[1].trim();
      current = SECTION_ORDER.includes(name) ? name : null;
      continue;
    }

    if (!current) {
      continue;
    }

    const item = line.match(ITEM_RE);
    if (!item) {
      continue;
    }

    items.push({
      status: current,
      area: item[2].trim(),
      text: item[3].trim(),
    });
  }

  return items;
}

function render(items) {
  const header = [
    "# Roadmap (Generated)",
    "",
    "> This file is autogenerated. Edit `docs/ROADMAP.md` and run `pnpm roadmap:gen`.",
    "",
    "| Area | Item | Status |",
    "| --- | --- | --- |",
  ];

  const rows = [];
  for (const section of SECTION_ORDER) {
    const sectionItems = items.filter((i) => i.status === section);
    for (const item of sectionItems) {
      rows.push(`| ${item.area} | ${item.text} | ${STATUS_LABELS[section]} |`);
    }
  }

  return [...header, ...rows, ""].join("\n");
}

const source = fs.readFileSync(SOURCE, "utf8");
const items = parseRoadmap(source);
const out = render(items);
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out);
